package cz.adsb.czadsb.model

enum class IconTypeEnum(val iconName: String) {
    A380("type_a380"),
    A340("type_a340"),
    AIRPLANE("generic"),
    BALL("balloon"),
    CAR("auto"),
    CAR_FIRE("fire"),
    CAR_FOLLOW_ME("followme"),
    F16("f16"),                                 // missing
    GLFX("type_glfx"),
    GLIDER("type_glid"),
    GROUND_VEHICLE("groundvehicle"),
    HELICOPTER("helicopter"),
    HELICOPTER_MEDICAL("helicopter_medical"),
    HELICOPTER_MILITARY("helicopter_military"),
    RADAR("radar"),
    TOWER("tower"),
    TURBO_PROP_4("four_turboprop"),
    TURBO_PROP_MIL_4("four_turboprop_mil"),
    TURBO_PROP_MIL_2("wtc_medium_2_turbo_mil"),
    UFO("ufo"),
    WTC_LIGHT_1_PROP("wtc_light_1_prop"),
    WTC_LIGHT_2_PROP("wtc_light_2_prop"),
    WTC_HEAWY_MIL_2_JET("wtc_heavy_mil_2_jet"),
    WTC_HEAVY_MIL_4_JET("wtc_heavy_mil_4_jet"),
    WTC_MEDIUM_4_JET("wtc_medium_4_jet"),
    WTC_MEDIUM_2_JET("wtc_medium_2_jet"),
    WTC_MEDIUM_2_TURBO("wtc_medium_2_turbo"),
    WTC_HEAVY_4_JET("wtc_heavy_4_jet"),
    WTC_HEAVY_2_JET("wtc_heavy_2_jet"),
}